#!/bin/sh

lb config noauto \
	--apt aptitude \
	--architecture amd64 \
	--packages-lists 'gnome-desktop dissomniag' \
	--bootappend-live "locales=de_DE.UTF-8 keyboard-layouts=de" \
	--language de \
	--syslinux-timeout 1 \
	"${@}"

