#!/bin/sh

lb config noauto \
        --mode debian \
        --distribution squeeze \
        --apt aptitude \
        --architecture i386 \
        --package-lists 'gnome dissomniag' \
        --bootappend-live "username=user locales=de_DE.UTF-8 keyboard-layouts=de" \
        --tasks 'german german-desktop german-gnome-desktop' \
        --boot config \
        -m http://localhost/debian
		"${@}"

