#!/bin/sh
# DiSSOmniaG (Distributed Simulation Service wit OMNeT++ and Git)
# Copyright (C) 2011, 2012 Sebastian Wallat, University Duisburg-Essen
# 
# Based on an idea of:
# Sebastian Wallat <sebastian.wallat@uni-due.de, University Duisburg-Essen
# Hakim Adhari <hakim.adhari@iem.uni-due.de>, University Duisburg-Essen
# Martin Becke <martin.becke@iem.uni-due.de>, University Duisburg-Essen
#
# DiSSOmniaG is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# DiSSOmniaG is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with DiSSOmniaG. If not, see <http://www.gnu.org/licenses/>
cwd=$(pwd)

cd ../

tar cvzpf DissomniagLive.tgz DiSSOmniaG_liveClient/
rm $cwd/config/includes.binary/DissomniagLive.tgz
#rm $cwd/binary/DissomniagLive.tgz
mv DissomniagLive.tgz $cwd/config/includes.binary/
cp DiSSOmniaG/static/live/init.d/dissomniag_live $cwd/config/includes.binary/

cd $cwd
echo $cwd

rm .build/binary_includes
rm .build/binary_local-includes
rm .build/binary_checksums
rm .build/binary_iso
